@baseUrl = http://localhost:3000

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "Victor Lucas A.",
    "email": "victorlucas.ao3@mctech.com",
    "password": "123456"
}