@baseUrl = http://localhost:3000
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "Victor Lucas A.",
    "email": "victorlucas.ao3@mctech.com",
    "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "victorlucas.ao3@mctech.com",
    "password": "123456"
}

###

# @name questions
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{}